### ISSUE TITLE
Store assets on Git LFS

### ISSUE THREAD

**Issue by Abendstolz** [bonsairobo/building-blocks-editor#2]
Hello!

I couldn't find anything on that matter in the readme, but `albedo.png` is missing. Not a big deal for sure, I just created my own, but I wanted to raise an issue in case it was overlooked.

**Comment by bonsairobo** [comment]
Hi, Abensdstolz,

Yea I don't think this was intentional but more of a missed opportunity. I would like to enable Git LFS to store assets.

Here is the image I've been using locally: https://github.com/bevyengine/bevy/blob/master/assets/textures/array_texture.png
